music/urls.py
from django.conf.urls import url
from. import  views
app_name='music'
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^(?P<album_Name_id>[0-9]+)$',views.detail,name='detail'),
    url(r'^(?P<album_Name_id>[0-9]+)/favorite$',views.favorite,name='favorite'),
]

musicapp/urls.py
from django.conf.urls import  include , url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/models.py
from django.db import  models

class Album(models.Model):
    shilpi=models.CharField(max_length=200)
    album_Name = models.CharField(max_length=200)
    Genre= models.CharField(max_length=200)
    logo=models.CharField(max_length=300)
    video=models.CharField(max_length=600,default='')

    def __str__(self):
     return self.shilpi


class Song(models.Model):
    album=models.ForeignKey(Album,on_delete=models.CASCADE)
    Gaan_title = models.CharField(max_length=400)
    fav=models.BooleanField(default=False)

    def __str__(self):
     return self.Gaan_title

music/views.py
from django.shortcuts import render,get_object_or_404
from .models import Album,Song


def index(request):
    albumm = Album.objects.all()
    context= dict( albumm=albumm )

    return render(request,'music/index.html',context)



def detail(request, album_Name_id):
    alb=get_object_or_404(Album,pk=album_Name_id)

    return render(request,'music/detail.html',{'alb':alb})

def favorite(request, album_Name_id):
    alb=get_object_or_404(Album,pk=album_Name_id)
    try:
        selected=alb.song_set.get(pk=request.POST['song'])
    except (KeyError,Song.DoesNotExist):


     return render(request,'music/detail.html',
                  {'alb':alb,
                   'error_message':"invalid", })
    else:
        selected.fav=True
        selected.save()
        return render( request, 'music/detail.html', {'alb': alb} )

templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %} viber {% endblock %}</title>


  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load staticfiles %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{%static 'music/style.css' %}"/>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'music:index' %}">ekra</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'music:index' %}">
        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
          Albums
      </a>
      </li>
         <li class="active"><a href="#">
        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
          Songs
      </a>
      </li>
     <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'music:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
    <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
    </ul>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/music/detail.html
{% extends 'music/base.html' %}
<title>{% block title %} album details {% endblock %}</title>
{% block body %}

<body class="page2">
<h1>{{ alb.shilpi }}</h1>
<h2>{{ alb.album_Name }}</h2>

{% if error_message %}
<p><strong> {{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'music:favorite' alb.id %}" class="formsong" method="post">

{% csrf_token %}
    {% for song in alb.song_set.all %}
    <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">

        <label for="song{{ forloop.counter }}">
        {{ song.Gaan_title }}
        {% if song.fav %}
        <img src="http://i.imgur.com/b9b13Rd.png"/>
        {% endif %}

        </label><br>

    {% endfor %}

<input type="submit" value="favorite">
</form>
</body>
{% endblock %}

templates/music/index.html
{% extends 'music/base.html' %}
{% block body %}
<h2>List</h2>


{% if albumm %}
<ul>
    {% for alb in albumm %}
    <li class="fc"><a class="c" href="{% url 'music:detail' alb.id %}">{{ alb.album_Name }} </> </li>
    {% endfor %}
</ul>
{% else %}
<h3>no album found</h3>
{% endif %}
{% endblock %}